name: Backend CI

on:
  pull_request:
    branches:
      - main
    paths:
      - "apps/backend/**"
      - ".github/workflows/backend_ci.yml"

jobs:
  codecov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm & install dependencies
        uses: pnpm/action-setup@v3
        with:
          version: 8.9.0
          run_install: true
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DIRECT_URL: ${{ secrets.DIRECT_URL}}

      - name: Run tests
        run: pnpm --filter backend test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
